# Generated by Django 3.1 on 2020-08-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200828_0251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItemModel',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ShippingAddressModel',
            new_name='ShippingAddress',
        ),
    ]
